# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec23276dc0c34c16950c81ce47eec4192a4179f85496a7e94466a61ac179ccb0205ffe7a8a2162ea774e8955aee798fff990e187910289e5a4eddecd28be0758

test:
  secret_key_base: c7fee934bb8aaff2b22f975a88fb4e9e0a6c6d6fe7cd590d9ee2659f1637cc2f30ca1041e43e4a0976bf162dff34a5045beb316e7f6b0c317255c6fc84e454d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
